version: '3.5'
services:
  api_gateway:
    image: golang:1.14
    working_dir: /go/src/github.com/lcnascimento/istio-knative-poc/api-gateway
    command: go run server.go
    env_file: 
      - api-gateway/config/.env
    ports:
      - "8080:8080"
    volumes:
      - ./go-libs:/go/src/github.com/lcnascimento/istio-knative-poc/go-libs
      - ./api-gateway:/go/src/github.com/lcnascimento/istio-knative-poc/api-gateway
      - ./segments-service:/go/src/github.com/lcnascimento/istio-knative-poc/segments-service
      - ./notifications-service:/go/src/github.com/lcnascimento/istio-knative-poc/notifications-service
      - ./exports-service:/go/src/github.com/lcnascimento/istio-knative-poc/exports-service
      - ./audiences-service:/go/src/github.com/lcnascimento/istio-knative-poc/audiences-service
      - "api-gateway-pkgs:/go"
    depends_on:
      - segments_service_frontend
      - notifications_service_frontend
      - notifications_service_worker
      - exports_service_frontend
      - audiences_service_frontend
      - jaeger
    container_name: api_gateway

  segments_service_frontend:
    image: golang:1.14
    working_dir: /go/src/github.com/lcnascimento/istio-knative-poc/segments-service
    command: go run cmd/grpc/frontend/main.go
    env_file: 
      - segments-service/config/.env
    ports:
      - "3001:3001"
    volumes:
      - ./go-libs:/go/src/github.com/lcnascimento/istio-knative-poc/go-libs
      - ./segments-service:/go/src/github.com/lcnascimento/istio-knative-poc/segments-service
      - "segments-service-frontend-pkgs:/go"
    container_name: segments_service_frontend

  notifications_service_frontend:
    image: golang:1.14
    working_dir: /go/src/github.com/lcnascimento/istio-knative-poc/notifications-service
    command: go run cmd/grpc/frontend/main.go
    env_file: 
      - notifications-service/config/.env
    ports:
      - "3002:3000"
    volumes:
      - ./go-libs:/go/src/github.com/lcnascimento/istio-knative-poc/go-libs
      - ./notifications-service:/go/src/github.com/lcnascimento/istio-knative-poc/notifications-service
      - ./segments-service:/go/src/github.com/lcnascimento/istio-knative-poc/segments-service
      - "notifications-service-frontend-pkgs:/go"
    depends_on:
      - jaeger
    container_name: notifications_service_frontend

  notifications_service_worker:
    image: golang:1.14
    working_dir: /go/src/github.com/lcnascimento/istio-knative-poc/notifications-service
    command: go run cmd/grpc/worker/main.go
    env_file: 
      - notifications-service/config/.env
    ports:
      - "3003:3000"
    volumes:
      - ./go-libs:/go/src/github.com/lcnascimento/istio-knative-poc/go-libs
      - ./notifications-service:/go/src/github.com/lcnascimento/istio-knative-poc/notifications-service
      - ./segments-service:/go/src/github.com/lcnascimento/istio-knative-poc/segments-service
      - "notifications-service-worker-pkgs:/go"
    depends_on:
      - segments_service_frontend
    container_name: notifications_service_worker

  exports_service_frontend:
    image: golang:1.14
    working_dir: /go/src/github.com/lcnascimento/istio-knative-poc/exports-service
    command: go run cmd/grpc/frontend/main.go
    env_file: 
      - exports-service/config/.env
    ports:
      - "3004:3000"
    volumes:
      - ./go-libs:/go/src/github.com/lcnascimento/istio-knative-poc/go-libs
      - ./exports-service:/go/src/github.com/lcnascimento/istio-knative-poc/exports-service
      - ./segments-service:/go/src/github.com/lcnascimento/istio-knative-poc/segments-service
      - "exports-service-frontend-pkgs:/go"
    container_name: exports_service_frontend

  exports_service_worker:
    image: golang:1.14
    working_dir: /go/src/github.com/lcnascimento/istio-knative-poc/exports-service
    command: go run cmd/grpc/worker/main.go
    env_file: 
      - exports-service/config/.env
    ports:
      - "3005:3000"
    volumes:
      - ./go-libs:/go/src/github.com/lcnascimento/istio-knative-poc/go-libs
      - ./exports-service:/go/src/github.com/lcnascimento/istio-knative-poc/exports-service
      - ./segments-service:/go/src/github.com/lcnascimento/istio-knative-poc/segments-service
      - "exports-service-worker-pkgs:/go"
    depends_on:
      - segments_service_frontend
    container_name: exports_service_worker

  audiences_service_frontend:
    image: golang:1.14
    working_dir: /go/src/github.com/lcnascimento/istio-knative-poc/audiences-service
    command: go run cmd/grpc/frontend/main.go
    env_file: 
      - audiences-service/config/.env
    ports:
      - "3006:3000"
    volumes:
      - ./go-libs:/go/src/github.com/lcnascimento/istio-knative-poc/go-libs
      - ./audiences-service:/go/src/github.com/lcnascimento/istio-knative-poc/audiences-service
      - ./exports-service:/go/src/github.com/lcnascimento/istio-knative-poc/exports-service
      - ./segments-service:/go/src/github.com/lcnascimento/istio-knative-poc/segments-service
      - "audiences-service-frontend-pkgs:/go"
    depends_on:
      - exports_service_frontend
    container_name: audiences_service_frontend
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "14268:14268"
      - "16686:16686"
    container_name: istio_knative_poc_jaeger
  
  prometheus:
    image: prom/prometheus:v2.14.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - segments_service_frontend
      - notifications_service_frontend
      - notifications_service_worker
      - exports_service_frontend
      - audiences_service_frontend
    container_name: istio_knative_poc_prometheus

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=dito
      - GF_SECURITY_ADMIN_PASSWORD=dito2017
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - jaeger
    ports:
      - "9091:3000"
    container_name: istio_knative_poc_grafana

volumes:
  api-gateway-pkgs:
  segments-service-frontend-pkgs:
  notifications-service-frontend-pkgs:
  notifications-service-worker-pkgs:
  exports-service-frontend-pkgs:
  exports-service-worker-pkgs:
  audiences-service-frontend-pkgs:
  grafana-data:
    