// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SegmentsServiceClient is the client API for SegmentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SegmentsServiceClient interface {
	GetSegment(ctx context.Context, in *GetSegmentRequest, opts ...grpc.CallOption) (*GetSegmentResponse, error)
	GetSegmentUsers(ctx context.Context, in *GetSegmentUsersRequest, opts ...grpc.CallOption) (SegmentsService_GetSegmentUsersClient, error)
}

type segmentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSegmentsServiceClient(cc grpc.ClientConnInterface) SegmentsServiceClient {
	return &segmentsServiceClient{cc}
}

func (c *segmentsServiceClient) GetSegment(ctx context.Context, in *GetSegmentRequest, opts ...grpc.CallOption) (*GetSegmentResponse, error) {
	out := new(GetSegmentResponse)
	err := c.cc.Invoke(ctx, "/grpc.SegmentsService/GetSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentsServiceClient) GetSegmentUsers(ctx context.Context, in *GetSegmentUsersRequest, opts ...grpc.CallOption) (SegmentsService_GetSegmentUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SegmentsService_serviceDesc.Streams[0], "/grpc.SegmentsService/GetSegmentUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &segmentsServiceGetSegmentUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SegmentsService_GetSegmentUsersClient interface {
	Recv() (*GetSegmentUsersResponse, error)
	grpc.ClientStream
}

type segmentsServiceGetSegmentUsersClient struct {
	grpc.ClientStream
}

func (x *segmentsServiceGetSegmentUsersClient) Recv() (*GetSegmentUsersResponse, error) {
	m := new(GetSegmentUsersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SegmentsServiceServer is the server API for SegmentsService service.
// All implementations must embed UnimplementedSegmentsServiceServer
// for forward compatibility
type SegmentsServiceServer interface {
	GetSegment(context.Context, *GetSegmentRequest) (*GetSegmentResponse, error)
	GetSegmentUsers(*GetSegmentUsersRequest, SegmentsService_GetSegmentUsersServer) error
	mustEmbedUnimplementedSegmentsServiceServer()
}

// UnimplementedSegmentsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSegmentsServiceServer struct {
}

func (UnimplementedSegmentsServiceServer) GetSegment(context.Context, *GetSegmentRequest) (*GetSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSegment not implemented")
}
func (UnimplementedSegmentsServiceServer) GetSegmentUsers(*GetSegmentUsersRequest, SegmentsService_GetSegmentUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSegmentUsers not implemented")
}
func (UnimplementedSegmentsServiceServer) mustEmbedUnimplementedSegmentsServiceServer() {}

// UnsafeSegmentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SegmentsServiceServer will
// result in compilation errors.
type UnsafeSegmentsServiceServer interface {
	mustEmbedUnimplementedSegmentsServiceServer()
}

func RegisterSegmentsServiceServer(s grpc.ServiceRegistrar, srv SegmentsServiceServer) {
	s.RegisterService(&_SegmentsService_serviceDesc, srv)
}

func _SegmentsService_GetSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentsServiceServer).GetSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.SegmentsService/GetSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentsServiceServer).GetSegment(ctx, req.(*GetSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentsService_GetSegmentUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSegmentUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SegmentsServiceServer).GetSegmentUsers(m, &segmentsServiceGetSegmentUsersServer{stream})
}

type SegmentsService_GetSegmentUsersServer interface {
	Send(*GetSegmentUsersResponse) error
	grpc.ServerStream
}

type segmentsServiceGetSegmentUsersServer struct {
	grpc.ServerStream
}

func (x *segmentsServiceGetSegmentUsersServer) Send(m *GetSegmentUsersResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SegmentsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.SegmentsService",
	HandlerType: (*SegmentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSegment",
			Handler:    _SegmentsService_GetSegment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSegmentUsers",
			Handler:       _SegmentsService_GetSegmentUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "application/grpc/proto/segments.proto",
}
